version: 2
project_name: sqlfs

builds:
  - id: static
    dir: ./src
    main: ./cmd/sqlfs
    binary: sqlfs
    env:
      - CGO_ENABLED=0
    flags:
      - -tags=netgo,osusergo,timetzdata
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: curl-installer
    builds:
      - static
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

release:
  draft: false
  prerelease: auto
